name: untitled2
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-98.0.dev

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  mysql1: ^0.19.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
